In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.datasets import fetch_20newsgroups
twenty = fetch_20newsgroups()

tfidf = TfidfVectorizer().fit_transform(twenty.data)
tfidf

<11314x130107 sparse matrix of type '<class 'numpy.float64'>'
	with 1787565 stored elements in Compressed Sparse Row format>

In [2]:
tfidf[0:1]

<1x130107 sparse matrix of type '<class 'numpy.float64'>'
	with 89 stored elements in Compressed Sparse Row format>

In [29]:
from sklearn.metrics.pairwise import linear_kernel
cosine_similarities = linear_kernel(tfidf[2:3], tfidf).flatten()
cosine_similarities

array([0.11017033, 0.06242113, 1.        , ..., 0.07569182, 0.06214891,
       0.02357985])

In [30]:
related_docs_indices = cosine_similarities.argsort()[:-6:-1]
related_docs_indices

array([   2, 2741,  913, 6894, 1904])

In [31]:
cosine_similarities[related_docs_indices]

array([1.        , 0.25746211, 0.25578851, 0.25181591, 0.25069756])

In [32]:
twenty['data'][2]

'From: twillis@ec.ecn.purdue.edu (Thomas E Willis)\nSubject: PB questions...\nOrganization: Purdue University Engineering Computer Network\nDistribution: usa\nLines: 36\n\nwell folks, my mac plus finally gave up the ghost this weekend after\nstarting life as a 512k way back in 1985.  sooo, i\'m in the market for a\nnew machine a bit sooner than i intended to be...\n\ni\'m looking into picking up a powerbook 160 or maybe 180 and have a bunch\nof questions that (hopefully) somebody can answer:\n\n* does anybody know any dirt on when the next round of powerbook\nintroductions are expected?  i\'d heard the 185c was supposed to make an\nappearence "this summer" but haven\'t heard anymore on it - and since i\ndon\'t have access to macleak, i was wondering if anybody out there had\nmore info...\n\n* has anybody heard rumors about price drops to the powerbook line like the\nones the duo\'s just went through recently?\n\n* what\'s the impression of the display on the 180?  i could probably swin

In [34]:
twenty['data'][913]

'From: bobbe@vice.ICO.TEK.COM (Robert Beauchaine)\nSubject: Nostalgia\nOrganization: Tektronix Inc., Beaverton, Or.\nLines: 1049\n\n\n  The recent rise of nostalgia in this group, combined with the\n  incredible level of utter bullshit, has prompted me to comb\n  through my archives and pull out some of "The Best of Alt.Atheism"\n  for your reading pleasure.  I\'ll post a couple of these a day\n  unless group concensus demands that I stop, or I run out of good\n  material.\n\n  I haven\'t been particularly careful in the past about saving\n  attributions.  I think the following comes from John A. Johnson,\n  but someone correct me if I\'m wrong.  This is probably the longest\n  of my entire collection.\n\n________________________________________________________\n\n\n                                  So that the\n                                  Prophecy be\n                                   Fulfilled\n\n                                     * * *\n\n       In considering the Christian